### ISSUE TITLE
pcre.so : image not found

### ISSUE THREAD

**Issue by snowe2010** [rummik/zsh-ing#1]
```
/Users/tylerthrailkill/.zgen/rummik/zsh-ing-master/ing.plugin.zsh:3: failed to load module `zsh/pcre': dlopen(/usr/local/Cellar/zsh/5.4.2_3/lib/zsh/pcre.so, 9): image not found
```

**Comment by rummik** [comment]
Sounds like the Zsh PCRE module hasn't been installed on your system.  I'm guessing from the path that you're using Homebrew.  It looks like someone was having a similar issue over at zplug/zplug#457, and the solution was to install Zsh with the flag `--with-pcre`

**Comment by rummik** [comment]
@snowe2010 Does that resolve your issue?

**Comment by snowe2010** [comment]
sorry I was on vacation until today. 

That resolved that error but now results in this error:

```
➜ ing google.com
ing:2: maximum nested function level reached; increase FUNCNEST?
```

**Comment by rummik** [comment]
Setting FUNCNEST to 0 is the only way I'm able to get a similar error.  It seems to default on my system to 500

```
> print $FUNCNEST
500
```

**Comment by snowe2010** [comment]
dang. I have mine already set to 500!

```
~
➜ ing google.com
ing:2: maximum nested function level reached; increase FUNCNEST?

~ took 2s
➜ print $FUNCNEST
500
```

**Comment by rummik** [comment]
This sounds like it's an issue caused by another plugin

**Comment by snowe2010** [comment]
I disabled all plugins except `ing` and tried again and received the same result.

**Comment by rummik** [comment]
Is your theme handling the time check?

**Comment by snowe2010** [comment]
Not sure what you mean, but I disabled all plugins including my theme (spaceship prompt) and it still occurred.

**Comment by rummik** [comment]
I'm at a bit of a loss then.  I can't reproduce over here, and it seems to be working fine down to FUNCNEST=1

**Comment by rummik** [comment]
Best I can try is removing the PCRE requirement and seeing if that fixes it.  I've pushed that change up -- let me know if it helps

**Comment by snowe2010** [comment]
dang. still encountering it. Oh well. thank you for trying so hard. Seems I won't be able to use `ing` 😭 

Note: I did try increasing FUNCNEST to 2000, but I just get no output with that :/

```
.zgen on  master
➜ ing google.com
ing:2: maximum nested function level reached; increase FUNCNEST?

.zgen on  master
➜ echo $FUNCNEST
500

.zgen on  master
➜ export FUNCNEST=2000

.zgen on  master
➜ ing google.com
```

**Comment by rummik** [comment]
So weird.  Sorry I couldn't be of more help! :sweat_smile:
